const actionTypes = {
  FETCH_ALBUMS: {
    START: "ALBUMS_START",
    SUCCESS: "ALBUMS_SUCCESS",
    FAILURE: "ALBUMS_FAILURE",
  },
  FETCH_ARTIST: {
    START: "ARTIST_START",
    SUCCESS: "ARTIST_SUCCESS",
    FAILURE: "ARTIST_FAILURE",
  },
  GET_INPUT: "GET_INPUT",
  SET_FAVORITE: "SET_FAVORITE",
  SET_FAVORITE_ARTIST: "SET_FAVORITE_ARTIST",
};

export default actionTypes;
